package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuxiliarId generated by hbm2java
 */
@Embeddable
public class AuxiliarId implements java.io.Serializable {

	private long idEmpresa;
	private int idTipo;
	private int idAux;

	public AuxiliarId() {
	}

	public AuxiliarId(long idEmpresa, int idTipo, int idAux) {
		this.idEmpresa = idEmpresa;
		this.idTipo = idTipo;
		this.idAux = idAux;
	}

	@Column(name = "idEmpresa", nullable = false)
	public long getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(long idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "idTipo", nullable = false)
	public int getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(int idTipo) {
		this.idTipo = idTipo;
	}

	@Column(name = "idAux", nullable = false)
	public int getIdAux() {
		return this.idAux;
	}

	public void setIdAux(int idAux) {
		this.idAux = idAux;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuxiliarId))
			return false;
		AuxiliarId castOther = (AuxiliarId) other;

		return (this.getIdEmpresa() == castOther.getIdEmpresa())
				&& (this.getIdTipo() == castOther.getIdTipo())
				&& (this.getIdAux() == castOther.getIdAux());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdEmpresa();
		result = 37 * result + this.getIdTipo();
		result = 37 * result + this.getIdAux();
		return result;
	}

}
