package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Depto generated by hbm2java
 */
@Entity
@Table(name = "depto", catalog = "fitdata", uniqueConstraints = @UniqueConstraint(columnNames = {
		"idEmpresa", "nomeDepto" }))
public class Depto implements java.io.Serializable {

	private DeptoId id;
	private Empresa empresa;
	private String nomeDepto;
	private String descDepto;
	private char flagSituacao;
	private char flagSistema;
	private Date dataLogUpdate;
	private String usuarioLogUpdate;
	private Date dataLogInclusao;
	private String usuarioLogInclusao;
	private Set<Usuariodetalhe> usuariodetalhes = new HashSet<Usuariodetalhe>(0);

	public Depto() {
	}

	public Depto(DeptoId id, Empresa empresa, String nomeDepto,
			char flagSituacao, char flagSistema, Date dataLogUpdate,
			String usuarioLogUpdate, Date dataLogInclusao,
			String usuarioLogInclusao) {
		this.id = id;
		this.empresa = empresa;
		this.nomeDepto = nomeDepto;
		this.flagSituacao = flagSituacao;
		this.flagSistema = flagSistema;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
	}

	public Depto(DeptoId id, Empresa empresa, String nomeDepto,
			String descDepto, char flagSituacao, char flagSistema,
			Date dataLogUpdate, String usuarioLogUpdate, Date dataLogInclusao,
			String usuarioLogInclusao, Set<Usuariodetalhe> usuariodetalhes) {
		this.id = id;
		this.empresa = empresa;
		this.nomeDepto = nomeDepto;
		this.descDepto = descDepto;
		this.flagSituacao = flagSituacao;
		this.flagSistema = flagSistema;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
		this.usuariodetalhes = usuariodetalhes;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idEmpresa", column = @Column(name = "idEmpresa", nullable = false)),
			@AttributeOverride(name = "idDepto", column = @Column(name = "idDepto", nullable = false)) })
	public DeptoId getId() {
		return this.id;
	}

	public void setId(DeptoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpresa", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nomeDepto", nullable = false, length = 15)
	public String getNomeDepto() {
		return this.nomeDepto;
	}

	public void setNomeDepto(String nomeDepto) {
		this.nomeDepto = nomeDepto;
	}

	@Column(name = "descDepto", length = 50)
	public String getDescDepto() {
		return this.descDepto;
	}

	public void setDescDepto(String descDepto) {
		this.descDepto = descDepto;
	}

	@Column(name = "flagSituacao", nullable = false, length = 1)
	public char getFlagSituacao() {
		return this.flagSituacao;
	}

	public void setFlagSituacao(char flagSituacao) {
		this.flagSituacao = flagSituacao;
	}

	@Column(name = "flagSistema", nullable = false, length = 1)
	public char getFlagSistema() {
		return this.flagSistema;
	}

	public void setFlagSistema(char flagSistema) {
		this.flagSistema = flagSistema;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogUpdate", nullable = false, length = 19)
	public Date getDataLogUpdate() {
		return this.dataLogUpdate;
	}

	public void setDataLogUpdate(Date dataLogUpdate) {
		this.dataLogUpdate = dataLogUpdate;
	}

	@Column(name = "usuarioLogUpdate", nullable = false, length = 15)
	public String getUsuarioLogUpdate() {
		return this.usuarioLogUpdate;
	}

	public void setUsuarioLogUpdate(String usuarioLogUpdate) {
		this.usuarioLogUpdate = usuarioLogUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogInclusao", nullable = false, length = 19)
	public Date getDataLogInclusao() {
		return this.dataLogInclusao;
	}

	public void setDataLogInclusao(Date dataLogInclusao) {
		this.dataLogInclusao = dataLogInclusao;
	}

	@Column(name = "usuarioLogInclusao", nullable = false, length = 15)
	public String getUsuarioLogInclusao() {
		return this.usuarioLogInclusao;
	}

	public void setUsuarioLogInclusao(String usuarioLogInclusao) {
		this.usuarioLogInclusao = usuarioLogInclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "depto")
	public Set<Usuariodetalhe> getUsuariodetalhes() {
		return this.usuariodetalhes;
	}

	public void setUsuariodetalhes(Set<Usuariodetalhe> usuariodetalhes) {
		this.usuariodetalhes = usuariodetalhes;
	}

}
