package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", catalog = "fitdata", uniqueConstraints = @UniqueConstraint(columnNames = "numeroDocumento"))
public class Empresa implements java.io.Serializable {

	private long idEmpresa;
	private long numeroDocumento;
	private String razaoSocial;
	private String enderecoRua;
	private String enderecoNumero;
	private String enderecoComplemento;
	private String enderecoBairro;
	private String enderecoCep;
	private String enderecoMunicipio;
	private String enderecoUf;
	private String email;
	private String telefone1;
	private String telefone2;
	private String telefone3;
	private String numeroCcm;
	private String inscricaoEstadual;
	private String inscricaoMunicipal;
	private String flagSituacao;
	private String flagSistema;
	private Date dataLogUpdate;
	private String usuarioLogUpdate;
	private Date dataLogInclusao;
	private String usuarioLogInclusao;
	private Set<Parametrosacesso> parametrosacessos = new HashSet<Parametrosacesso>(
			0);
	private Set<Sistema> sistemas = new HashSet<Sistema>(0);
	private Set<Funcao> funcaos = new HashSet<Funcao>(0);
	private Set<Perfil> perfils = new HashSet<Perfil>(0);
	private Set<Licenca> licencas = new HashSet<Licenca>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Parametros> parametroses = new HashSet<Parametros>(0);
	private Set<Usuariodetalhe> usuariodetalhes = new HashSet<Usuariodetalhe>(0);
	private Set<Tipoauxiliar> tipoauxiliars = new HashSet<Tipoauxiliar>(0);
	private Set<Perfilfuncao> perfilfuncaos = new HashSet<Perfilfuncao>(0);
	private Set<Depto> deptos = new HashSet<Depto>(0);

	public Empresa() {
	}

	public Empresa(long idEmpresa, long numeroDocumento, String razaoSocial,
			String flagSituacao, String flagSistema, Date dataLogUpdate,
			String usuarioLogUpdate, Date dataLogInclusao,
			String usuarioLogInclusao) {
		this.idEmpresa = idEmpresa;
		this.numeroDocumento = numeroDocumento;
		this.razaoSocial = razaoSocial;
		this.flagSituacao = flagSituacao;
		this.flagSistema = flagSistema;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
	}

	public Empresa(long idEmpresa, long numeroDocumento, String razaoSocial,
			String enderecoRua, String enderecoNumero,
			String enderecoComplemento, String enderecoBairro,
			String enderecoCep, String enderecoMunicipio, String enderecoUf,
			String email, String telefone1, String telefone2, String telefone3,
			String numeroCcm, String inscricaoEstadual,
			String inscricaoMunicipal, String flagSituacao, String flagSistema,
			Date dataLogUpdate, String usuarioLogUpdate, Date dataLogInclusao,
			String usuarioLogInclusao, Set<Parametrosacesso> parametrosacessos,
			Set<Sistema> sistemas, Set<Funcao> funcaos, Set<Perfil> perfils,
			Set<Licenca> licencas, Set<Usuario> usuarios,
			Set<Parametros> parametroses, Set<Usuariodetalhe> usuariodetalhes,
			Set<Tipoauxiliar> tipoauxiliars, Set<Perfilfuncao> perfilfuncaos,
			Set<Depto> deptos) {
		this.idEmpresa = idEmpresa;
		this.numeroDocumento = numeroDocumento;
		this.razaoSocial = razaoSocial;
		this.enderecoRua = enderecoRua;
		this.enderecoNumero = enderecoNumero;
		this.enderecoComplemento = enderecoComplemento;
		this.enderecoBairro = enderecoBairro;
		this.enderecoCep = enderecoCep;
		this.enderecoMunicipio = enderecoMunicipio;
		this.enderecoUf = enderecoUf;
		this.email = email;
		this.telefone1 = telefone1;
		this.telefone2 = telefone2;
		this.telefone3 = telefone3;
		this.numeroCcm = numeroCcm;
		this.inscricaoEstadual = inscricaoEstadual;
		this.inscricaoMunicipal = inscricaoMunicipal;
		this.flagSituacao = flagSituacao;
		this.flagSistema = flagSistema;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
		this.parametrosacessos = parametrosacessos;
		this.sistemas = sistemas;
		this.funcaos = funcaos;
		this.perfils = perfils;
		this.licencas = licencas;
		this.usuarios = usuarios;
		this.parametroses = parametroses;
		this.usuariodetalhes = usuariodetalhes;
		this.tipoauxiliars = tipoauxiliars;
		this.perfilfuncaos = perfilfuncaos;
		this.deptos = deptos;
	}

	@Id
	@Column(name = "idEmpresa", unique = true, nullable = false)
	public long getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(long idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "numeroDocumento", unique = true, nullable = false)
	public long getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(long numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@Column(name = "razaoSocial", nullable = false, length = 200)
	public String getRazaoSocial() {
		return this.razaoSocial;
	}

	public void setRazaoSocial(String razaoSocial) {
		this.razaoSocial = razaoSocial;
	}

	@Column(name = "enderecoRua", length = 100)
	public String getEnderecoRua() {
		return this.enderecoRua;
	}

	public void setEnderecoRua(String enderecoRua) {
		this.enderecoRua = enderecoRua;
	}

	@Column(name = "enderecoNumero", length = 6)
	public String getEnderecoNumero() {
		return this.enderecoNumero;
	}

	public void setEnderecoNumero(String enderecoNumero) {
		this.enderecoNumero = enderecoNumero;
	}

	@Column(name = "enderecoComplemento", length = 45)
	public String getEnderecoComplemento() {
		return this.enderecoComplemento;
	}

	public void setEnderecoComplemento(String enderecoComplemento) {
		this.enderecoComplemento = enderecoComplemento;
	}

	@Column(name = "enderecoBairro", length = 60)
	public String getEnderecoBairro() {
		return this.enderecoBairro;
	}

	public void setEnderecoBairro(String enderecoBairro) {
		this.enderecoBairro = enderecoBairro;
	}

	@Column(name = "enderecoCEP", length = 15)
	public String getEnderecoCep() {
		return this.enderecoCep;
	}

	public void setEnderecoCep(String enderecoCep) {
		this.enderecoCep = enderecoCep;
	}

	@Column(name = "enderecoMunicipio", length = 60)
	public String getEnderecoMunicipio() {
		return this.enderecoMunicipio;
	}

	public void setEnderecoMunicipio(String enderecoMunicipio) {
		this.enderecoMunicipio = enderecoMunicipio;
	}

	@Column(name = "enderecoUF", length = 5)
	public String getEnderecoUf() {
		return this.enderecoUf;
	}

	public void setEnderecoUf(String enderecoUf) {
		this.enderecoUf = enderecoUf;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefone1", length = 20)
	public String getTelefone1() {
		return this.telefone1;
	}

	public void setTelefone1(String telefone1) {
		this.telefone1 = telefone1;
	}

	@Column(name = "telefone2", length = 20)
	public String getTelefone2() {
		return this.telefone2;
	}

	public void setTelefone2(String telefone2) {
		this.telefone2 = telefone2;
	}

	@Column(name = "telefone3", length = 20)
	public String getTelefone3() {
		return this.telefone3;
	}

	public void setTelefone3(String telefone3) {
		this.telefone3 = telefone3;
	}

	@Column(name = "numeroCCM", length = 45)
	public String getNumeroCcm() {
		return this.numeroCcm;
	}

	public void setNumeroCcm(String numeroCcm) {
		this.numeroCcm = numeroCcm;
	}

	@Column(name = "inscricaoEstadual", length = 45)
	public String getInscricaoEstadual() {
		return this.inscricaoEstadual;
	}

	public void setInscricaoEstadual(String inscricaoEstadual) {
		this.inscricaoEstadual = inscricaoEstadual;
	}

	@Column(name = "inscricaoMunicipal", length = 45)
	public String getInscricaoMunicipal() {
		return this.inscricaoMunicipal;
	}

	public void setInscricaoMunicipal(String inscricaoMunicipal) {
		this.inscricaoMunicipal = inscricaoMunicipal;
	}

	@Column(name = "flagSituacao", nullable = false, length = 45)
	public String getFlagSituacao() {
		return this.flagSituacao;
	}

	public void setFlagSituacao(String flagSituacao) {
		this.flagSituacao = flagSituacao;
	}

	@Column(name = "flagSistema", nullable = false, length = 45)
	public String getFlagSistema() {
		return this.flagSistema;
	}

	public void setFlagSistema(String flagSistema) {
		this.flagSistema = flagSistema;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogUpdate", nullable = false, length = 19)
	public Date getDataLogUpdate() {
		return this.dataLogUpdate;
	}

	public void setDataLogUpdate(Date dataLogUpdate) {
		this.dataLogUpdate = dataLogUpdate;
	}

	@Column(name = "usuarioLogUpdate", nullable = false, length = 15)
	public String getUsuarioLogUpdate() {
		return this.usuarioLogUpdate;
	}

	public void setUsuarioLogUpdate(String usuarioLogUpdate) {
		this.usuarioLogUpdate = usuarioLogUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogInclusao", nullable = false, length = 19)
	public Date getDataLogInclusao() {
		return this.dataLogInclusao;
	}

	public void setDataLogInclusao(Date dataLogInclusao) {
		this.dataLogInclusao = dataLogInclusao;
	}

	@Column(name = "usuarioLogInclusao", nullable = false, length = 15)
	public String getUsuarioLogInclusao() {
		return this.usuarioLogInclusao;
	}

	public void setUsuarioLogInclusao(String usuarioLogInclusao) {
		this.usuarioLogInclusao = usuarioLogInclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Parametrosacesso> getParametrosacessos() {
		return this.parametrosacessos;
	}

	public void setParametrosacessos(Set<Parametrosacesso> parametrosacessos) {
		this.parametrosacessos = parametrosacessos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Sistema> getSistemas() {
		return this.sistemas;
	}

	public void setSistemas(Set<Sistema> sistemas) {
		this.sistemas = sistemas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Funcao> getFuncaos() {
		return this.funcaos;
	}

	public void setFuncaos(Set<Funcao> funcaos) {
		this.funcaos = funcaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Licenca> getLicencas() {
		return this.licencas;
	}

	public void setLicencas(Set<Licenca> licencas) {
		this.licencas = licencas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Parametros> getParametroses() {
		return this.parametroses;
	}

	public void setParametroses(Set<Parametros> parametroses) {
		this.parametroses = parametroses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Usuariodetalhe> getUsuariodetalhes() {
		return this.usuariodetalhes;
	}

	public void setUsuariodetalhes(Set<Usuariodetalhe> usuariodetalhes) {
		this.usuariodetalhes = usuariodetalhes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Tipoauxiliar> getTipoauxiliars() {
		return this.tipoauxiliars;
	}

	public void setTipoauxiliars(Set<Tipoauxiliar> tipoauxiliars) {
		this.tipoauxiliars = tipoauxiliars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Perfilfuncao> getPerfilfuncaos() {
		return this.perfilfuncaos;
	}

	public void setPerfilfuncaos(Set<Perfilfuncao> perfilfuncaos) {
		this.perfilfuncaos = perfilfuncaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Depto> getDeptos() {
		return this.deptos;
	}

	public void setDeptos(Set<Depto> deptos) {
		this.deptos = deptos;
	}

}
