package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Funcao generated by hbm2java
 */
@Entity
@Table(name = "funcao", catalog = "fitdata", uniqueConstraints = @UniqueConstraint(columnNames = {
		"idEmpresa", "idSistema", "nomeFuncao" }))
public class Funcao implements java.io.Serializable {

	private FuncaoId id;
	private Empresa empresa;
	private Sistema sistema;
	private String nomeFuncao;
	private String descricaoFuncao;
	private char flagSituacao;
	private Date dataLogUpdate;
	private String usuarioLogUpdate;
	private Date dataLogInclusao;
	private String usuarioLogInclusao;
	private Set<Perfilfuncao> perfilfuncaos = new HashSet<Perfilfuncao>(0);

	public Funcao() {
	}

	public Funcao(FuncaoId id, Empresa empresa, Sistema sistema,
			String nomeFuncao, String descricaoFuncao, char flagSituacao,
			Date dataLogUpdate, String usuarioLogUpdate, Date dataLogInclusao,
			String usuarioLogInclusao) {
		this.id = id;
		this.empresa = empresa;
		this.sistema = sistema;
		this.nomeFuncao = nomeFuncao;
		this.descricaoFuncao = descricaoFuncao;
		this.flagSituacao = flagSituacao;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
	}

	public Funcao(FuncaoId id, Empresa empresa, Sistema sistema,
			String nomeFuncao, String descricaoFuncao, char flagSituacao,
			Date dataLogUpdate, String usuarioLogUpdate, Date dataLogInclusao,
			String usuarioLogInclusao, Set<Perfilfuncao> perfilfuncaos) {
		this.id = id;
		this.empresa = empresa;
		this.sistema = sistema;
		this.nomeFuncao = nomeFuncao;
		this.descricaoFuncao = descricaoFuncao;
		this.flagSituacao = flagSituacao;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
		this.perfilfuncaos = perfilfuncaos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idEmpresa", column = @Column(name = "idEmpresa", nullable = false)),
			@AttributeOverride(name = "idFuncao", column = @Column(name = "idFuncao", nullable = false)) })
	public FuncaoId getId() {
		return this.id;
	}

	public void setId(FuncaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpresa", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "idEmpresa", referencedColumnName = "idEmpresa", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "idSistema", referencedColumnName = "idSistema", nullable = false, insertable = false, updatable = false) })
	public Sistema getSistema() {
		return this.sistema;
	}

	public void setSistema(Sistema sistema) {
		this.sistema = sistema;
	}

	@Column(name = "nomeFuncao", nullable = false, length = 20)
	public String getNomeFuncao() {
		return this.nomeFuncao;
	}

	public void setNomeFuncao(String nomeFuncao) {
		this.nomeFuncao = nomeFuncao;
	}

	@Column(name = "descricaoFuncao", nullable = false, length = 200)
	public String getDescricaoFuncao() {
		return this.descricaoFuncao;
	}

	public void setDescricaoFuncao(String descricaoFuncao) {
		this.descricaoFuncao = descricaoFuncao;
	}

	@Column(name = "flagSituacao", nullable = false, length = 1)
	public char getFlagSituacao() {
		return this.flagSituacao;
	}

	public void setFlagSituacao(char flagSituacao) {
		this.flagSituacao = flagSituacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogUpdate", nullable = false, length = 19)
	public Date getDataLogUpdate() {
		return this.dataLogUpdate;
	}

	public void setDataLogUpdate(Date dataLogUpdate) {
		this.dataLogUpdate = dataLogUpdate;
	}

	@Column(name = "usuarioLogUpdate", nullable = false, length = 15)
	public String getUsuarioLogUpdate() {
		return this.usuarioLogUpdate;
	}

	public void setUsuarioLogUpdate(String usuarioLogUpdate) {
		this.usuarioLogUpdate = usuarioLogUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogInclusao", nullable = false, length = 19)
	public Date getDataLogInclusao() {
		return this.dataLogInclusao;
	}

	public void setDataLogInclusao(Date dataLogInclusao) {
		this.dataLogInclusao = dataLogInclusao;
	}

	@Column(name = "usuarioLogInclusao", nullable = false, length = 15)
	public String getUsuarioLogInclusao() {
		return this.usuarioLogInclusao;
	}

	public void setUsuarioLogInclusao(String usuarioLogInclusao) {
		this.usuarioLogInclusao = usuarioLogInclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcao")
	public Set<Perfilfuncao> getPerfilfuncaos() {
		return this.perfilfuncaos;
	}

	public void setPerfilfuncaos(Set<Perfilfuncao> perfilfuncaos) {
		this.perfilfuncaos = perfilfuncaos;
	}

}
