package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParametrosacessoId generated by hbm2java
 */
@Embeddable
public class ParametrosacessoId implements java.io.Serializable {

	private long idEmpresa;
	private String idParam;

	public ParametrosacessoId() {
	}

	public ParametrosacessoId(long idEmpresa, String idParam) {
		this.idEmpresa = idEmpresa;
		this.idParam = idParam;
	}

	@Column(name = "idEmpresa", nullable = false)
	public long getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(long idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "idParam", nullable = false, length = 5)
	public String getIdParam() {
		return this.idParam;
	}

	public void setIdParam(String idParam) {
		this.idParam = idParam;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParametrosacessoId))
			return false;
		ParametrosacessoId castOther = (ParametrosacessoId) other;

		return (this.getIdEmpresa() == castOther.getIdEmpresa())
				&& ((this.getIdParam() == castOther.getIdParam()) || (this
						.getIdParam() != null && castOther.getIdParam() != null && this
						.getIdParam().equals(castOther.getIdParam())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdEmpresa();
		result = 37 * result
				+ (getIdParam() == null ? 0 : this.getIdParam().hashCode());
		return result;
	}

}
