package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfilfuncaoId generated by hbm2java
 */
@Embeddable
public class PerfilfuncaoId implements java.io.Serializable {

	private long idEmpresa;
	private int idPerfil;
	private int idFuncao;

	public PerfilfuncaoId() {
	}

	public PerfilfuncaoId(long idEmpresa, int idPerfil, int idFuncao) {
		this.idEmpresa = idEmpresa;
		this.idPerfil = idPerfil;
		this.idFuncao = idFuncao;
	}

	@Column(name = "idEmpresa", nullable = false)
	public long getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(long idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "idPerfil", nullable = false)
	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "idFuncao", nullable = false)
	public int getIdFuncao() {
		return this.idFuncao;
	}

	public void setIdFuncao(int idFuncao) {
		this.idFuncao = idFuncao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfilfuncaoId))
			return false;
		PerfilfuncaoId castOther = (PerfilfuncaoId) other;

		return (this.getIdEmpresa() == castOther.getIdEmpresa())
				&& (this.getIdPerfil() == castOther.getIdPerfil())
				&& (this.getIdFuncao() == castOther.getIdFuncao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdEmpresa();
		result = 37 * result + this.getIdPerfil();
		result = 37 * result + this.getIdFuncao();
		return result;
	}

}
