package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfilId generated by hbm2java
 */
@Embeddable
public class PerfilId implements java.io.Serializable {

	private long idEmpresa;
	private int idPerfil;

	public PerfilId() {
	}

	public PerfilId(long idEmpresa, int idPerfil) {
		this.idEmpresa = idEmpresa;
		this.idPerfil = idPerfil;
	}

	@Column(name = "idEmpresa", nullable = false)
	public long getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(long idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "idPerfil", nullable = false)
	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfilId))
			return false;
		PerfilId castOther = (PerfilId) other;

		return (this.getIdEmpresa() == castOther.getIdEmpresa())
				&& (this.getIdPerfil() == castOther.getIdPerfil());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdEmpresa();
		result = 37 * result + this.getIdPerfil();
		return result;
	}

}
