package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", catalog = "fitdata")
public class Perfil implements java.io.Serializable {

	private PerfilId id;
	private Empresa empresa;
	private Sistema sistema;
	private String nomePerfil;
	private String descricaoPerfil;
	private char flagSituacao;
	private Date dataLogUpdate;
	private String usuarioLogUpdate;
	private Date dataLogInclusao;
	private String usuarioLogInclusao;
	private char flagSistema;
	private Set<Usuarioperfil> usuarioperfils = new HashSet<Usuarioperfil>(0);
	private Set<Perfilfuncao> perfilfuncaos = new HashSet<Perfilfuncao>(0);

	public Perfil() {
	}

	public Perfil(PerfilId id, Empresa empresa, Sistema sistema,
			String nomePerfil, char flagSituacao, Date dataLogUpdate,
			String usuarioLogUpdate, Date dataLogInclusao,
			String usuarioLogInclusao, char flagSistema) {
		this.id = id;
		this.empresa = empresa;
		this.sistema = sistema;
		this.nomePerfil = nomePerfil;
		this.flagSituacao = flagSituacao;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
		this.flagSistema = flagSistema;
	}

	public Perfil(PerfilId id, Empresa empresa, Sistema sistema,
			String nomePerfil, String descricaoPerfil, char flagSituacao,
			Date dataLogUpdate, String usuarioLogUpdate, Date dataLogInclusao,
			String usuarioLogInclusao, char flagSistema,
			Set<Usuarioperfil> usuarioperfils, Set<Perfilfuncao> perfilfuncaos) {
		this.id = id;
		this.empresa = empresa;
		this.sistema = sistema;
		this.nomePerfil = nomePerfil;
		this.descricaoPerfil = descricaoPerfil;
		this.flagSituacao = flagSituacao;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
		this.flagSistema = flagSistema;
		this.usuarioperfils = usuarioperfils;
		this.perfilfuncaos = perfilfuncaos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idEmpresa", column = @Column(name = "idEmpresa", nullable = false)),
			@AttributeOverride(name = "idPerfil", column = @Column(name = "idPerfil", nullable = false)) })
	public PerfilId getId() {
		return this.id;
	}

	public void setId(PerfilId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpresa", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "idEmpresa", referencedColumnName = "idEmpresa", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "idSistema", referencedColumnName = "idSistema", nullable = false, insertable = false, updatable = false) })
	public Sistema getSistema() {
		return this.sistema;
	}

	public void setSistema(Sistema sistema) {
		this.sistema = sistema;
	}

	@Column(name = "nomePerfil", nullable = false, length = 20)
	public String getNomePerfil() {
		return this.nomePerfil;
	}

	public void setNomePerfil(String nomePerfil) {
		this.nomePerfil = nomePerfil;
	}

	@Column(name = "descricaoPerfil", length = 200)
	public String getDescricaoPerfil() {
		return this.descricaoPerfil;
	}

	public void setDescricaoPerfil(String descricaoPerfil) {
		this.descricaoPerfil = descricaoPerfil;
	}

	@Column(name = "flagSituacao", nullable = false, length = 1)
	public char getFlagSituacao() {
		return this.flagSituacao;
	}

	public void setFlagSituacao(char flagSituacao) {
		this.flagSituacao = flagSituacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogUpdate", nullable = false, length = 19)
	public Date getDataLogUpdate() {
		return this.dataLogUpdate;
	}

	public void setDataLogUpdate(Date dataLogUpdate) {
		this.dataLogUpdate = dataLogUpdate;
	}

	@Column(name = "usuarioLogUpdate", nullable = false, length = 15)
	public String getUsuarioLogUpdate() {
		return this.usuarioLogUpdate;
	}

	public void setUsuarioLogUpdate(String usuarioLogUpdate) {
		this.usuarioLogUpdate = usuarioLogUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogInclusao", nullable = false, length = 19)
	public Date getDataLogInclusao() {
		return this.dataLogInclusao;
	}

	public void setDataLogInclusao(Date dataLogInclusao) {
		this.dataLogInclusao = dataLogInclusao;
	}

	@Column(name = "usuarioLogInclusao", nullable = false, length = 15)
	public String getUsuarioLogInclusao() {
		return this.usuarioLogInclusao;
	}

	public void setUsuarioLogInclusao(String usuarioLogInclusao) {
		this.usuarioLogInclusao = usuarioLogInclusao;
	}

	@Column(name = "flagSistema", nullable = false, length = 1)
	public char getFlagSistema() {
		return this.flagSistema;
	}

	public void setFlagSistema(char flagSistema) {
		this.flagSistema = flagSistema;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Usuarioperfil> getUsuarioperfils() {
		return this.usuarioperfils;
	}

	public void setUsuarioperfils(Set<Usuarioperfil> usuarioperfils) {
		this.usuarioperfils = usuarioperfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Perfilfuncao> getPerfilfuncaos() {
		return this.perfilfuncaos;
	}

	public void setPerfilfuncaos(Set<Perfilfuncao> perfilfuncaos) {
		this.perfilfuncaos = perfilfuncaos;
	}

}
