package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sistema generated by hbm2java
 */
@Entity
@Table(name = "sistema", catalog = "fitdata")
public class Sistema implements java.io.Serializable {

	private SistemaId id;
	private Empresa empresa;
	private String nomeSistema;
	private String descricaoSistema;
	private String siglaSistema;
	private String usuarioAdmin1;
	private String usuarioAdmin2;
	private char flagLog;
	private int mesesLog;
	private int mesesExpira;
	private int minutosBloqueio;
	private char flagSituacao;
	private Date dataLogUpdate;
	private String usuarioLogUpdate;
	private Date dataLogInclusao;
	private String usuarioLogInclusao;
	private Set<Usuariosistema> usuariosistemas = new HashSet<Usuariosistema>(0);
	private Set<Funcao> funcaos = new HashSet<Funcao>(0);
	private Set<Perfil> perfils = new HashSet<Perfil>(0);

	public Sistema() {
	}

	public Sistema(SistemaId id, Empresa empresa, String nomeSistema,
			char flagLog, int mesesLog, int mesesExpira, int minutosBloqueio,
			char flagSituacao, Date dataLogUpdate, String usuarioLogUpdate,
			Date dataLogInclusao, String usuarioLogInclusao) {
		this.id = id;
		this.empresa = empresa;
		this.nomeSistema = nomeSistema;
		this.flagLog = flagLog;
		this.mesesLog = mesesLog;
		this.mesesExpira = mesesExpira;
		this.minutosBloqueio = minutosBloqueio;
		this.flagSituacao = flagSituacao;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
	}

	public Sistema(SistemaId id, Empresa empresa, String nomeSistema,
			String descricaoSistema, String siglaSistema, String usuarioAdmin1,
			String usuarioAdmin2, char flagLog, int mesesLog, int mesesExpira,
			int minutosBloqueio, char flagSituacao, Date dataLogUpdate,
			String usuarioLogUpdate, Date dataLogInclusao,
			String usuarioLogInclusao, Set<Usuariosistema> usuariosistemas,
			Set<Funcao> funcaos, Set<Perfil> perfils) {
		this.id = id;
		this.empresa = empresa;
		this.nomeSistema = nomeSistema;
		this.descricaoSistema = descricaoSistema;
		this.siglaSistema = siglaSistema;
		this.usuarioAdmin1 = usuarioAdmin1;
		this.usuarioAdmin2 = usuarioAdmin2;
		this.flagLog = flagLog;
		this.mesesLog = mesesLog;
		this.mesesExpira = mesesExpira;
		this.minutosBloqueio = minutosBloqueio;
		this.flagSituacao = flagSituacao;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
		this.usuariosistemas = usuariosistemas;
		this.funcaos = funcaos;
		this.perfils = perfils;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idEmpresa", column = @Column(name = "idEmpresa", nullable = false)),
			@AttributeOverride(name = "idSistema", column = @Column(name = "idSistema", nullable = false)) })
	public SistemaId getId() {
		return this.id;
	}

	public void setId(SistemaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpresa", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nomeSistema", nullable = false, length = 50)
	public String getNomeSistema() {
		return this.nomeSistema;
	}

	public void setNomeSistema(String nomeSistema) {
		this.nomeSistema = nomeSistema;
	}

	@Column(name = "descricaoSistema", length = 200)
	public String getDescricaoSistema() {
		return this.descricaoSistema;
	}

	public void setDescricaoSistema(String descricaoSistema) {
		this.descricaoSistema = descricaoSistema;
	}

	@Column(name = "siglaSistema", length = 5)
	public String getSiglaSistema() {
		return this.siglaSistema;
	}

	public void setSiglaSistema(String siglaSistema) {
		this.siglaSistema = siglaSistema;
	}

	@Column(name = "usuarioAdmin1", length = 15)
	public String getUsuarioAdmin1() {
		return this.usuarioAdmin1;
	}

	public void setUsuarioAdmin1(String usuarioAdmin1) {
		this.usuarioAdmin1 = usuarioAdmin1;
	}

	@Column(name = "usuarioAdmin2", length = 15)
	public String getUsuarioAdmin2() {
		return this.usuarioAdmin2;
	}

	public void setUsuarioAdmin2(String usuarioAdmin2) {
		this.usuarioAdmin2 = usuarioAdmin2;
	}

	@Column(name = "flagLog", nullable = false, length = 1)
	public char getFlagLog() {
		return this.flagLog;
	}

	public void setFlagLog(char flagLog) {
		this.flagLog = flagLog;
	}

	@Column(name = "mesesLog", nullable = false)
	public int getMesesLog() {
		return this.mesesLog;
	}

	public void setMesesLog(int mesesLog) {
		this.mesesLog = mesesLog;
	}

	@Column(name = "mesesExpira", nullable = false)
	public int getMesesExpira() {
		return this.mesesExpira;
	}

	public void setMesesExpira(int mesesExpira) {
		this.mesesExpira = mesesExpira;
	}

	@Column(name = "minutosBloqueio", nullable = false)
	public int getMinutosBloqueio() {
		return this.minutosBloqueio;
	}

	public void setMinutosBloqueio(int minutosBloqueio) {
		this.minutosBloqueio = minutosBloqueio;
	}

	@Column(name = "flagSituacao", nullable = false, length = 1)
	public char getFlagSituacao() {
		return this.flagSituacao;
	}

	public void setFlagSituacao(char flagSituacao) {
		this.flagSituacao = flagSituacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogUpdate", nullable = false, length = 19)
	public Date getDataLogUpdate() {
		return this.dataLogUpdate;
	}

	public void setDataLogUpdate(Date dataLogUpdate) {
		this.dataLogUpdate = dataLogUpdate;
	}

	@Column(name = "usuarioLogUpdate", nullable = false, length = 15)
	public String getUsuarioLogUpdate() {
		return this.usuarioLogUpdate;
	}

	public void setUsuarioLogUpdate(String usuarioLogUpdate) {
		this.usuarioLogUpdate = usuarioLogUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogInclusao", nullable = false, length = 19)
	public Date getDataLogInclusao() {
		return this.dataLogInclusao;
	}

	public void setDataLogInclusao(Date dataLogInclusao) {
		this.dataLogInclusao = dataLogInclusao;
	}

	@Column(name = "usuarioLogInclusao", nullable = false, length = 15)
	public String getUsuarioLogInclusao() {
		return this.usuarioLogInclusao;
	}

	public void setUsuarioLogInclusao(String usuarioLogInclusao) {
		this.usuarioLogInclusao = usuarioLogInclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	public Set<Usuariosistema> getUsuariosistemas() {
		return this.usuariosistemas;
	}

	public void setUsuariosistemas(Set<Usuariosistema> usuariosistemas) {
		this.usuariosistemas = usuariosistemas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	public Set<Funcao> getFuncaos() {
		return this.funcaos;
	}

	public void setFuncaos(Set<Funcao> funcaos) {
		this.funcaos = funcaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

}
