package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 12:23:52 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Table1 generated by hbm2java
 */
@Entity
@Table(name = "table1", catalog = "fitdata")
public class Table1 implements java.io.Serializable {

	private int idItem;
	private Table2 table2;
	private String descItem;

	public Table1() {
	}

	public Table1(int idItem) {
		this.idItem = idItem;
	}

	public Table1(int idItem, Table2 table2, String descItem) {
		this.idItem = idItem;
		this.table2 = table2;
		this.descItem = descItem;
	}

	@Id
	@Column(name = "idItem", unique = true, nullable = false)
	public int getIdItem() {
		return this.idItem;
	}

	public void setIdItem(int idItem) {
		this.idItem = idItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCliente")
	public Table2 getTable2() {
		return this.table2;
	}

	public void setTable2(Table2 table2) {
		this.table2 = table2;
	}

	@Column(name = "descItem", length = 45)
	public String getDescItem() {
		return this.descItem;
	}

	public void setDescItem(String descItem) {
		this.descItem = descItem;
	}

}
