package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TipoauxiliarId generated by hbm2java
 */
@Embeddable
public class TipoauxiliarId implements java.io.Serializable {

	private long idEmpresa;
	private int idTipo;

	public TipoauxiliarId() {
	}

	public TipoauxiliarId(long idEmpresa, int idTipo) {
		this.idEmpresa = idEmpresa;
		this.idTipo = idTipo;
	}

	@Column(name = "idEmpresa", nullable = false)
	public long getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(long idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "idTipo", nullable = false)
	public int getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(int idTipo) {
		this.idTipo = idTipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoauxiliarId))
			return false;
		TipoauxiliarId castOther = (TipoauxiliarId) other;

		return (this.getIdEmpresa() == castOther.getIdEmpresa())
				&& (this.getIdTipo() == castOther.getIdTipo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdEmpresa();
		result = 37 * result + this.getIdTipo();
		return result;
	}

}
