package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuariosistemaId generated by hbm2java
 */
@Embeddable
public class UsuariosistemaId implements java.io.Serializable {

	private String idUsuario;
	private long idEmpresa;
	private int idSistema;

	public UsuariosistemaId() {
	}

	public UsuariosistemaId(String idUsuario, long idEmpresa, int idSistema) {
		this.idUsuario = idUsuario;
		this.idEmpresa = idEmpresa;
		this.idSistema = idSistema;
	}

	@Column(name = "idUsuario", nullable = false, length = 15)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "idEmpresa", nullable = false)
	public long getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(long idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "idSistema", nullable = false)
	public int getIdSistema() {
		return this.idSistema;
	}

	public void setIdSistema(int idSistema) {
		this.idSistema = idSistema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuariosistemaId))
			return false;
		UsuariosistemaId castOther = (UsuariosistemaId) other;

		return ((this.getIdUsuario() == castOther.getIdUsuario()) || (this
				.getIdUsuario() != null && castOther.getIdUsuario() != null && this
				.getIdUsuario().equals(castOther.getIdUsuario())))
				&& (this.getIdEmpresa() == castOther.getIdEmpresa())
				&& (this.getIdSistema() == castOther.getIdSistema());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		result = 37 * result + (int) this.getIdEmpresa();
		result = 37 * result + this.getIdSistema();
		return result;
	}

}
