package br.com.fitsoft.fitdata.model;

// Generated 06/06/2013 09:53:01 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "fitdata")
public class Usuario implements java.io.Serializable {

	private String idUsuario;
	private Empresa empresa;
	private String senhaUsuario;
	private String nomeCompleto;
	private String apelidoUsuario;
	private Date dataCriacao;
	private Date dataTrocaSenha;
	private String perguntaSenha;
	private String respostaSenha;
	private char flagSituacao;
	private char flagBloqueado;
	private Integer numTentativas;
	private Date dataBloqueio;
	private Integer numTentativaResposta;
	private String senhaAnterior1;
	private String senhaAnterior2;
	private String senhaAnterior3;
	private char flagSistema;
	private Date dataLogUpdate;
	private String usuarioLogUpdate;
	private Date dataLogInclusao;
	private String usuarioLogInclusao;
	private Usuariodetalhe usuariodetalhe;
	private Set<Usuarioperfil> usuarioperfils = new HashSet<Usuarioperfil>(0);
	private Set<Usuariosistema> usuariosistemas = new HashSet<Usuariosistema>(0);

	public Usuario() {
	}

	public Usuario(String idUsuario, Empresa empresa, String senhaUsuario,
			String nomeCompleto, Date dataCriacao, char flagSituacao,
			char flagBloqueado, char flagSistema, Date dataLogUpdate,
			String usuarioLogUpdate, Date dataLogInclusao,
			String usuarioLogInclusao) {
		this.idUsuario = idUsuario;
		this.empresa = empresa;
		this.senhaUsuario = senhaUsuario;
		this.nomeCompleto = nomeCompleto;
		this.dataCriacao = dataCriacao;
		this.flagSituacao = flagSituacao;
		this.flagBloqueado = flagBloqueado;
		this.flagSistema = flagSistema;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
	}

	public Usuario(String idUsuario, Empresa empresa, String senhaUsuario,
			String nomeCompleto, String apelidoUsuario, Date dataCriacao,
			Date dataTrocaSenha, String perguntaSenha, String respostaSenha,
			char flagSituacao, char flagBloqueado, Integer numTentativas,
			Date dataBloqueio, Integer numTentativaResposta,
			String senhaAnterior1, String senhaAnterior2,
			String senhaAnterior3, char flagSistema, Date dataLogUpdate,
			String usuarioLogUpdate, Date dataLogInclusao,
			String usuarioLogInclusao, Usuariodetalhe usuariodetalhe,
			Set<Usuarioperfil> usuarioperfils,
			Set<Usuariosistema> usuariosistemas) {
		this.idUsuario = idUsuario;
		this.empresa = empresa;
		this.senhaUsuario = senhaUsuario;
		this.nomeCompleto = nomeCompleto;
		this.apelidoUsuario = apelidoUsuario;
		this.dataCriacao = dataCriacao;
		this.dataTrocaSenha = dataTrocaSenha;
		this.perguntaSenha = perguntaSenha;
		this.respostaSenha = respostaSenha;
		this.flagSituacao = flagSituacao;
		this.flagBloqueado = flagBloqueado;
		this.numTentativas = numTentativas;
		this.dataBloqueio = dataBloqueio;
		this.numTentativaResposta = numTentativaResposta;
		this.senhaAnterior1 = senhaAnterior1;
		this.senhaAnterior2 = senhaAnterior2;
		this.senhaAnterior3 = senhaAnterior3;
		this.flagSistema = flagSistema;
		this.dataLogUpdate = dataLogUpdate;
		this.usuarioLogUpdate = usuarioLogUpdate;
		this.dataLogInclusao = dataLogInclusao;
		this.usuarioLogInclusao = usuarioLogInclusao;
		this.usuariodetalhe = usuariodetalhe;
		this.usuarioperfils = usuarioperfils;
		this.usuariosistemas = usuariosistemas;
	}

	@Id
	@Column(name = "idUsuario", unique = true, nullable = false, length = 15)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "senhaUsuario", nullable = false, length = 50)
	public String getSenhaUsuario() {
		return this.senhaUsuario;
	}

	public void setSenhaUsuario(String senhaUsuario) {
		this.senhaUsuario = senhaUsuario;
	}

	@Column(name = "nomeCompleto", nullable = false, length = 200)
	public String getNomeCompleto() {
		return this.nomeCompleto;
	}

	public void setNomeCompleto(String nomeCompleto) {
		this.nomeCompleto = nomeCompleto;
	}

	@Column(name = "apelidoUsuario", length = 50)
	public String getApelidoUsuario() {
		return this.apelidoUsuario;
	}

	public void setApelidoUsuario(String apelidoUsuario) {
		this.apelidoUsuario = apelidoUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCriacao", nullable = false, length = 19)
	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataTrocaSenha", length = 19)
	public Date getDataTrocaSenha() {
		return this.dataTrocaSenha;
	}

	public void setDataTrocaSenha(Date dataTrocaSenha) {
		this.dataTrocaSenha = dataTrocaSenha;
	}

	@Column(name = "perguntaSenha", length = 100)
	public String getPerguntaSenha() {
		return this.perguntaSenha;
	}

	public void setPerguntaSenha(String perguntaSenha) {
		this.perguntaSenha = perguntaSenha;
	}

	@Column(name = "respostaSenha", length = 100)
	public String getRespostaSenha() {
		return this.respostaSenha;
	}

	public void setRespostaSenha(String respostaSenha) {
		this.respostaSenha = respostaSenha;
	}

	@Column(name = "flagSituacao", nullable = false, length = 1)
	public char getFlagSituacao() {
		return this.flagSituacao;
	}

	public void setFlagSituacao(char flagSituacao) {
		this.flagSituacao = flagSituacao;
	}

	@Column(name = "flagBloqueado", nullable = false, length = 1)
	public char getFlagBloqueado() {
		return this.flagBloqueado;
	}

	public void setFlagBloqueado(char flagBloqueado) {
		this.flagBloqueado = flagBloqueado;
	}

	@Column(name = "numTentativas")
	public Integer getNumTentativas() {
		return this.numTentativas;
	}

	public void setNumTentativas(Integer numTentativas) {
		this.numTentativas = numTentativas;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataBloqueio", length = 19)
	public Date getDataBloqueio() {
		return this.dataBloqueio;
	}

	public void setDataBloqueio(Date dataBloqueio) {
		this.dataBloqueio = dataBloqueio;
	}

	@Column(name = "numTentativaResposta")
	public Integer getNumTentativaResposta() {
		return this.numTentativaResposta;
	}

	public void setNumTentativaResposta(Integer numTentativaResposta) {
		this.numTentativaResposta = numTentativaResposta;
	}

	@Column(name = "senhaAnterior1", length = 50)
	public String getSenhaAnterior1() {
		return this.senhaAnterior1;
	}

	public void setSenhaAnterior1(String senhaAnterior1) {
		this.senhaAnterior1 = senhaAnterior1;
	}

	@Column(name = "senhaAnterior2", length = 50)
	public String getSenhaAnterior2() {
		return this.senhaAnterior2;
	}

	public void setSenhaAnterior2(String senhaAnterior2) {
		this.senhaAnterior2 = senhaAnterior2;
	}

	@Column(name = "senhaAnterior3", length = 50)
	public String getSenhaAnterior3() {
		return this.senhaAnterior3;
	}

	public void setSenhaAnterior3(String senhaAnterior3) {
		this.senhaAnterior3 = senhaAnterior3;
	}

	@Column(name = "flagSistema", nullable = false, length = 1)
	public char getFlagSistema() {
		return this.flagSistema;
	}

	public void setFlagSistema(char flagSistema) {
		this.flagSistema = flagSistema;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogUpdate", nullable = false, length = 19)
	public Date getDataLogUpdate() {
		return this.dataLogUpdate;
	}

	public void setDataLogUpdate(Date dataLogUpdate) {
		this.dataLogUpdate = dataLogUpdate;
	}

	@Column(name = "usuarioLogUpdate", nullable = false, length = 15)
	public String getUsuarioLogUpdate() {
		return this.usuarioLogUpdate;
	}

	public void setUsuarioLogUpdate(String usuarioLogUpdate) {
		this.usuarioLogUpdate = usuarioLogUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogInclusao", nullable = false, length = 19)
	public Date getDataLogInclusao() {
		return this.dataLogInclusao;
	}

	public void setDataLogInclusao(Date dataLogInclusao) {
		this.dataLogInclusao = dataLogInclusao;
	}

	@Column(name = "usuarioLogInclusao", nullable = false, length = 15)
	public String getUsuarioLogInclusao() {
		return this.usuarioLogInclusao;
	}

	public void setUsuarioLogInclusao(String usuarioLogInclusao) {
		this.usuarioLogInclusao = usuarioLogInclusao;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Usuariodetalhe getUsuariodetalhe() {
		return this.usuariodetalhe;
	}

	public void setUsuariodetalhe(Usuariodetalhe usuariodetalhe) {
		this.usuariodetalhe = usuariodetalhe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Usuarioperfil> getUsuarioperfils() {
		return this.usuarioperfils;
	}

	public void setUsuarioperfils(Set<Usuarioperfil> usuarioperfils) {
		this.usuarioperfils = usuarioperfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Usuariosistema> getUsuariosistemas() {
		return this.usuariosistemas;
	}

	public void setUsuariosistemas(Set<Usuariosistema> usuariosistemas) {
		this.usuariosistemas = usuariosistemas;
	}

}
